### ISSUE TITLE
Wrong parts?

### ISSUE THREAD

**Issue by buteomont** [MichMich/KiCad-SSD1306_OLED-0.91-128x32#1]
I downloaded the zip file for this repository and imported the .lib file into my KiCad (6.0.11). It showed as "Legacy" so I converted it, but the only parts that showed up were a capacitor and an SSD device. I'm new to KiCad so this may be something I did wrong. Can you put the display schematic up in the new format?

**Comment by MichMich** [comment]
The SSD device is probably the part you are looking for.

**Comment by buteomont** [comment]
Thanks, it probably is. I was looking for the version with only four pins, and didn't realize there were others that had more.
